### PR TITLE
Fix issue #22 by returning only errors for the last definition in an 'or'

### PR DESCRIPTION
**Pull request by Goltergaul**
I found a problem where the `error_hash` of a `ConformResult` was missing an error. The problem is a bit complex but the essence is that if we add all errors that are produced by all sub definitions of an Or-Definition then it can happen that no meaningful error hash can be built. This is the case when the error paths overlap in a way that a key of the error hash needs to be an array of errors and a hash at the same time. This does not work.

FYI: The errors were all generated correctly and validation works as expected and all errors are there. Rendering it as hash does fail.

I added a new Or integration test where this situation happens. In this particular spec we have the following definiton:
```ruby
definition = Definition.Or(
  Definition.Keys do
    required(:person, Definition.Keys do
      required(:first_name, Definition.Type(String))
    end) 
  end,
  Definition.Keys do
    required(:social_security_number, Definition.Type(String))
  end
)
```
if that is validated against this hash `{ person: { first_name: 1 } }` then we have errors for /person/first_name from the first branch of the or and errors for /person (unexpected key in second branch) and /social_security_number from the second branch. The problem occurs then that two error hashes would need to be merged together which are incompatible:
from branch one: `{person: { first_name: [error] }}` and from the second branch: `{ person: [error], social_security_number: [error]}` => the effect is that the first_name error gets lost.

To fix this problem I changed the error collection for Or definitions to only collect the errors of the last failing element. This has two advantages: 1) way less very confusing error messages for big Ors and 2) the error hash should be able to be built in any case this way

### CODE REVIEW

**Review by ZairaZafar — APPROVED** [review]

**Review by TheWudu — APPROVED** [review]

**Comment by erikpaperik** [comment]
How about not just returning the error_tree of the last failed definition check but the error_tree with the deepest `error_hash`?
Following your example: If you pass `{ person: { first_name: 1 } }`, it seams that your intention is more about building a hash with a `person` key instead of making use of a `social_security_number`.

**Comment by Goltergaul** [comment]
> How about not simply using the `error_tree` of the last failed definition check but the error_tree with the deepest `error_hash`? Following your example: If you pass `{ person: { first_name: 1 } }`, it seams that your intention is more about building a hash with a `person` key instead of making use of a `social_security_number`. The error_hash for the `person` check is deeper than for the `social_security_number` which would be a more meaningful error message in that case.

Interesting idea :thinking: However there would still be an error missing in this case, even if its the one that is probably less interesting. That somehow does not sound like a good thing to have

**Comment by erikpaperik** [comment]
> > How about not simply using the `error_tree` of the last failed definition check but the error_tree with the deepest `error_hash`? Following your example: If you pass `{ person: { first_name: 1 } }`, it seams that your intention is more about building a hash with a `person` key instead of making use of a `social_security_number`. The error_hash for the `person` check is deeper than for the `social_security_number` which would be a more meaningful error message in that case.
> 
> Interesting idea thinking However there would still be an error missing in this case, even if its the one that is probably less interesting. That somehow does not sound like a good consistent thing to have

Instead of having a missing error, the change introduced in this PR introduces an faulty error though.
In the scenario you described above, there will be a `"<Definition::ConformError \n\t message: \"hash has extra key: :person\", \n\t json_pointer: \"/person\">"` which is not true since it's not really an _extra_ key. It's just extra in the scope of the `social_security_number` example.

**Review by erikpaperik — APPROVED** [review]

**Comment by Goltergaul** [comment]
@erikpaperik thought about this a bit more now and found that in standard cases like this it would not help:

```
definition = Definition.Or(
  Definition.Keys do
    required(:last_name, Definition.Type(String))
    required(:first_name, Definition.Type(String))
  end,
  Definition.Keys do
    required(:social_security_number, Definition.Type(String))
  end
)
```

And i can think of many use cases where one would validate that an array consists of different hashes with different keys, but not necessarily different nesting depths. I think it is simpler to understand and use if the error reporting follows easy to understand rules?

**Pull request merged**
